### ISSUE TITLE
Things needed.

### ISSUE THREAD

**Issue by asyncthreading** [BlockHorizons/BlockPerms#1]
1. Permissions support
2. .yml file where groups are going to be stored, more likely it has to be like xperms group config
3. setgroup/addgroup/removegroup/setperm command
4. factionspro support maybe
5. Chat format stuff

**Comment by TheDiamondYT1** [comment]
This plugin will be updated at some point, when i feel like it. I don't think we'll have FactionsPro support initially as i **hate** the plugin. Why havent you updated your factions plugin yet?

**Comment by asyncthreading** [comment]
I wanted to say FactionsPE by BH, my bad.

**Comment by asyncthreading** [comment]
Is it going to support factionspe?

**Comment by Sandertv** [comment]
I would certainly assume so @akaSnapy. Likely FactionsPE and PocketFactions by @TheDiamondYT1

**Comment by asyncthreading** [comment]
Thats really cool @Sandertv . Good luck coding this

**Comment by TheDiamondYT1** [comment]
Im gonna rewrite PocketFactions

**Comment by Kris-Driv** [comment]
What do you mean by faction support? You are working with permission nodes.

**Comment by Sandertv** [comment]
@Chris-Prime once we actually have a chat part like PureChat.
